### ISSUE TITLE
Parameters for example plot?

### ISSUE THREAD

**Issue by edonnachie** [joweich/year-in-search-trends#2]
This is a very nice project with helpful code. Thank you!

I found the example plot on Mastodon, but it's not clear to me how this can be interpreted. Were the keywords normalised to the same scale, or should we not be comparing them (e.g. wordle more popular than the Queen)? What were the paramters used?

**Comment by joweich** [comment]
Hi @edonnachie,
Would you mind providing the link to the Mastodon post?
To answer your question: The keywords are all normalized to a scale between 1 and 100. You can't compare the popularity of any keywords against each other, as each keyword's maximum will be at 100.

**Comment by edonnachie** [comment]
This is the post I found it through. Via Reddit, it seems:

https://mastodon.social/@nixCraft/109550706200767825
